apiVersion: v1
kind: Service
metadata:
  name: deployer-app
  namespace: ashapp
spec:
  selector:
    app: deployer-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31002
  type: NodePort

